name: Run periodically the statistic csv and export it in a branch.


on:
  push:
    # Don't run for tags
    tags-ignore:
      - '*.*.*'
    branches:
      - '**'

jobs:
  push_csv_file:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'Warframe-market-tool/Warframe-market-tool.github.io'
          github-server-url: 'https://github.com'

      - name: Copy CSV files to target repository
        run: |
          touch test.csv
          cp test.csv csv/
        shell: bash
      
      - uses: fregante/setup-git-user@v2
      
      - name: Commit and push changes to target repository
        run: |
          git add -A
          git commit -m "Add latest CSV export"
          git push
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
