name: Run periodically the statistic csv and export it in a branch.


on:
  push:
    # Don't run for tags
    tags-ignore:
      - '*.*.*'
    branches:
      - '**'


jobs:
  export-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Get specific workflow run ID
      id: get-specific-run-id
      run: |
        # Fetch the workflow runs and find the run with the specified name
        run_id=$(gh api -X GET /repos/${{ github.repository }}/actions/runs | jq -r --arg name "Release 0.0.0" '.workflow_runs[] | select(.name == $name) | .id')
        echo "run_id=$run_id" >> $GITHUB_ENV
        echo "Run ID: $run_id"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List artifacts from the latest run
      id: list-artifacts
      run: |
        artifact_name=$(gh api -X GET /repos/${{ github.repository }}/actions/runs/${{ env.latest_run_id }}/artifacts | jq -r --arg name "${{ github.event.inputs.artifact_name }}" '.artifacts[] | select(.name == $name) | .name')
        echo "artifact_name=$artifact_name" >> $GITHUB_ENV
        echo "artifact_name=$artifact_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: WarframeMarketTool-latest
        path: dist/
        run-id: $env.latest_run_id

    - name: Update config.json with secrets
      run: |
        jq '.email = env.EMAIL' dist/config.json > dist/config.tmp && mv dist/config.tmp dist/config.json
        jq '.password = env.PASSWORD' dist/config.json > dist/config.tmp && mv dist/config.tmp dist/config.json
      env:
        EMAIL: ${{ secrets.WARFRAME_BOT_EMAIL }}
        PASSWORD: ${{ secrets.WARFRAME_BOT_PASSWORD }}

    - name: Run the artifact with --export-csv
      run: |
        chmod +x dist/WarframeMarketTool.exe
        ./dist/WarframeMarketTool.exe --export-csv
      shell: bash

    - name: Clone the target repository
      run: |
        git clone https://github.com/Warframe-market-tool/daily-stats-export.git daily-stats-export
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_daily-stats-export }}

    - name: Copy CSV files to target repository
      run: |
        cp dist/csv/*.csv daily-stats-export/
      shell: bash

    - name: Commit and push changes to target repository
      run: |
        cd daily-stats-export
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add latest CSV export"
        git push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_daily-stats-export }}