name: Build the powershell script to an executable and create an archive to download the program

on:
  release:
    types: [published]
permissions:
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Scope AllUsers -Force -AllowClobber
        Import-Module ps2exe
        Get-Command -Module ps2exe
      shell: powershell

    - name: Run build script
      run: |
        .\build.ps1
      shell: powershell
      
    - name: List files in dist directory
      run: dir dist
    
    - name: Upload folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: WarframeMarketTool-v${{ github.event.release.tag_name }}
        path: dist/
