name: Build the powershell script to an executable and create an archive to download the program

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow when a new tag is pushed, typically used for releases
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Scope AllUsers -Force -AllowClobber
        Import-Module ps2exe
        Get-Command -Module ps2exe
      shell: powershell

    - name: Run build script
      run: |
        .\build.ps1
      shell: powershell
      
    - name: List files in dist directory
      run: dir dist
    
    - name: Upload folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: WarframeMarketTool-v${{ github.event.release.tag_name }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Download the artifact from the link below.
      # Change this to 'true' if you want to publish the release immediately
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist
        asset_name: dist.zip
        asset_content_type: application/zip
