name: Build the powershell script to an executable and create an archive to download the program

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow when a new tag is pushed, typically used for releases
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Scope AllUsers -Force -AllowClobber
        Import-Module ps2exe
        Get-Command -Module ps2exe
      shell: powershell

    - name: Run build script
      run: |
        .\build.ps1
      shell: powershell
      
    - name: List files in dist directory
      run: dir dist
    
    - name: Upload folder as artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: WarframeMarketTool-${{ github.ref_name }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: dist
        path: dist

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ github.ref_name }}
        name: Release WarframeMarketTool-${{ github.ref_name }}
        body: |
          Download the artifact from the link below.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: WarframeMarketTool-${{ github.ref_name }}
        path: dist/
