name: Build the powershell script to an executable and create an archive to download the program

on:
  release:
    types: [published]
  push:
    branches:
      - github-action

permissions:
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PowerShell Toolkit
      uses: hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0
      with:
        # {Boolean} Whether to execute in sudo mode on non-Windows environment.
        sudo: # optional, default is False
        # {String} Target version.
        version: # optional, default is ^2.1.0
        # {Boolean} Whether to allow target pre release version.
        allowprerelease: # optional, default is False
        # {String} Installation scope.
        scope: # optional, default is CurrentUser
        # {Boolean} Whether to force install or reinstall target (pre release) version.
        force: # optional, default is False
        # {Boolean} Whether to keep the setting that modified.
        keepsetting: # optional, default is False
          
      
    - name: Install ps2exe module
      run: |
        Install-Module -Name ps2exe -Scope CurrentUser -Force -AllowClobber
      shell: pwsh

    - name: Run build script
      run: |
        .\build.cmd
      shell: cmd
    
    - name: List files in dist directory
      run: dir dist
    
    - name: Upload folder as artifact
      uses: actions/upload-artifact@v3
      with:
        name: WarframeMarketTool-v${{ github.event.release.tag_name }}
        path: dist/
